### ISSUE TITLE
考虑上gitbook，大家觉得如何？

### ISSUE THREAD

**Issue by i5ting** [base-n/koa-generator-examples#10]

**Comment by wewea** [comment]
支持一下, 阅读方便.

**Comment by yinzSE** [comment]
不知道是如何`一起学koa`
使用 `koa-generator` 初始化搭建一个论坛, 然后写一份使用文档吗?

**Comment by phantomk** [comment]
赞成上gitbook

**Comment by wodog** [comment]
支持啊

**Comment by i5ting** [comment]
加上了，大家看一下效果啊

http://base-n.github.io/koa-generator-examples

**Comment by i5ting** [comment]
目前已经使用gitbook了，发布在github pages上
