### ISSUE TITLE
关于贡献--源码分析部分

### ISSUE THREAD

**Issue by CoderIvan** [base-n/koa-generator-examples#47]
看这里的md，没有源码分析的部分，下面的文章应该怎么贡献出来？

> [Koa中间件功能源码阅读](https://cnodejs.org/topic/56a33e24cf60b1b94bab33f8)

**Comment by i5ting** [comment]
thanks

**Comment by CoderIvan** [comment]
意思是不需要，还是？

**Comment by i5ting** [comment]
@CoderIvan 需要的，O(∩_∩)O谢谢啊，最近比较忙，没有太多时间整理，已经记录了
